### ISSUE TITLE
cleanup, please

### ISSUE THREAD

**Issue by Kentrosaurus** [Kentrosaurus/MayaPy#1]
Here you go, Scott.  Please fix up and I'll take it from there

**Comment by sernst** [comment]
I've done the necessary cleanup to allow the application to launch into a blank window. I stopped some of the logic from the home and tools widgets that were specifying to Cadence but now should be done depending on what you want included in MayaPy.

Take a look and let me know what's missing or extraneous based on your vision of the GUI.

**Comment by Kentrosaurus** [comment]
Done, thanks.
